<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Governorate;
use App\Models\ShippingRate;
use Illuminate\Database\Seeder;

class GovernorateCitySeeder extends Seeder
{
    protected array $governorates = [
        ['name' => 'القاهرة', 'name_ar' => 'Cairo', 'base_shipping_cost' => 35],
        ['name' => 'الجيزة', 'name_ar' => 'Giza', 'base_shipping_cost' => 35],
        ['name' => 'الإسكندرية', 'name_ar' => 'Alexandria', 'base_shipping_cost' => 40],
        ['name' => 'الدقهلية', 'name_ar' => 'Dakahlia', 'base_shipping_cost' => 45],
        ['name' => 'الشرقية', 'name_ar' => 'Sharqia', 'base_shipping_cost' => 45],
        ['name' => 'البحيرة', 'name_ar' => 'Beheira', 'base_shipping_cost' => 45],
        ['name' => 'الغربية', 'name_ar' => 'Gharbia', 'base_shipping_cost' => 45],
        ['name' => 'المنوفية', 'name_ar' => 'Monufia', 'base_shipping_cost' => 45],
        ['name' => 'القليوبية', 'name_ar' => 'Qalyubia', 'base_shipping_cost' => 40],
        ['name' => 'الفيوم', 'name_ar' => 'Faiyum', 'base_shipping_cost' => 50],
        ['name' => 'بني سويف', 'name_ar' => 'Beni Suef', 'base_shipping_cost' => 50],
        ['name' => 'المنيا', 'name_ar' => 'Minya', 'base_shipping_cost' => 55],
        ['name' => 'أسيوط', 'name_ar' => 'Asyut', 'base_shipping_cost' => 55],
        ['name' => 'سوهاج', 'name_ar' => 'Sohag', 'base_shipping_cost' => 55],
        ['name' => 'قنا', 'name_ar' => 'Qena', 'base_shipping_cost' => 60],
        ['name' => 'الأقصر', 'name_ar' => 'Luxor', 'base_shipping_cost' => 60],
        ['name' => 'أسوان', 'name_ar' => 'Aswan', 'base_shipping_cost' => 65],
        ['name' => 'البحر الأحمر', 'name_ar' => 'Red Sea', 'base_shipping_cost' => 70],
        ['name' => 'الوادي الجديد', 'name_ar' => 'New Valley', 'base_shipping_cost' => 75],
        ['name' => 'مطروح', 'name_ar' => 'Matruh', 'base_shipping_cost' => 70],
        ['name' => 'شمال سيناء', 'name_ar' => 'North Sinai', 'base_shipping_cost' => 75],
        ['name' => 'جنوب سيناء', 'name_ar' => 'South Sinai', 'base_shipping_cost' => 75],
        ['name' => 'دمياط', 'name_ar' => 'Damietta', 'base_shipping_cost' => 45],
        ['name' => 'بورسعيد', 'name_ar' => 'Port Said', 'base_shipping_cost' => 45],
        ['name' => 'الإسماعيلية', 'name_ar' => 'Ismailia', 'base_shipping_cost' => 45],
        ['name' => 'السويس', 'name_ar' => 'Suez', 'base_shipping_cost' => 45],
        ['name' => 'كفر الشيخ', 'name_ar' => 'Kafr El Sheikh', 'base_shipping_cost' => 45],
    ];

    public function run(): void
    {
        if (Governorate::count() > 0) {
            $this->command->info('Governorates already seeded. Skipping.');
            return;
        }

        foreach ($this->governorates as $govData) {
            $gov = Governorate::create($govData);
            $this->seedCities($gov);
        }
    }

    protected function seedCities(Governorate $gov): void
    {
        $cities = match ($gov->name) {
            'القاهرة' => [
                ['name' => 'المعادي', 'delivery_time' => '1-2 يوم'],
                ['name' => 'مدينة نصر', 'delivery_time' => '1-2 يوم'],
                ['name' => 'مصر الجديدة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'التجمع الخامس', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الرحاب', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الشروق', 'delivery_time' => '1-2 يوم'],
                ['name' => 'المقطم', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الزمالك', 'delivery_time' => '1-2 يوم'],
                ['name' => 'وسط البلد', 'delivery_time' => '1-2 يوم'],
                ['name' => 'شبرا', 'delivery_time' => '1-2 يوم'],
                ['name' => 'العباسية', 'delivery_time' => '1-2 يوم'],
                ['name' => 'المطرية', 'delivery_time' => '1-2 يوم'],
                ['name' => 'عين شمس', 'delivery_time' => '1-2 يوم'],
                ['name' => 'حلوان', 'delivery_time' => '1-3 أيام'],
                ['name' => '15 مايو', 'delivery_time' => '1-3 أيام'],
                ['name' => 'المرج', 'delivery_time' => '1-2 يوم'],
                ['name' => 'مصر القديمة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'السيدة زينب', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الدراسة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الزيتون', 'delivery_time' => '1-2 يوم'],
                ['name' => 'حدائق القبة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'روض الفرج', 'delivery_time' => '1-2 يوم'],
                ['name' => 'بولاق', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الساحل', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الوايلي', 'delivery_time' => '1-2 يوم'],
                ['name' => 'التجمع الأول', 'delivery_time' => '1-2 يوم'],
                ['name' => 'مدينتي', 'delivery_time' => '1-2 يوم'],
                ['name' => 'بدر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'العاصمة الإدارية', 'delivery_time' => '1-3 أيام'],
            ],
            'الجيزة' => [
                ['name' => 'الدقي', 'delivery_time' => '1-2 يوم'],
                ['name' => 'المهندسين', 'delivery_time' => '1-2 يوم'],
                ['name' => 'العجوزة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الهرم', 'delivery_time' => '1-2 يوم'],
                ['name' => 'فيصل', 'delivery_time' => '1-2 يوم'],
                ['name' => '6 أكتوبر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الشيخ زايد', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أكتوبر الجديدة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الباويطي', 'delivery_time' => '2-4 أيام'],
                ['name' => 'إمبابة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الوراق', 'delivery_time' => '1-2 يوم'],
                ['name' => 'أوسيم', 'delivery_time' => '1-2 يوم'],
                ['name' => 'كرداسة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'البدرشين', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الصف', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أطفيح', 'delivery_time' => '1-3 أيام'],
                ['name' => 'العياط', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الحوامدية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'المنيب', 'delivery_time' => '1-2 يوم'],
                ['name' => 'بولاق الدكرور', 'delivery_time' => '1-2 يوم'],
            ],
            'الإسكندرية' => [
                ['name' => 'وسط المدينة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'سيدي بشر', 'delivery_time' => '1-2 يوم'],
                ['name' => 'محرم بك', 'delivery_time' => '1-2 يوم'],
                ['name' => 'المنتزه', 'delivery_time' => '1-2 يوم'],
                ['name' => 'العامرية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'برج العرب', 'delivery_time' => '1-3 أيام'],
                ['name' => 'سموحة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'محطة الرمل', 'delivery_time' => '1-2 يوم'],
                ['name' => 'لوران', 'delivery_time' => '1-2 يوم'],
                ['name' => 'كليوباترا', 'delivery_time' => '1-2 يوم'],
                ['name' => 'فيكتوريا', 'delivery_time' => '1-2 يوم'],
                ['name' => 'سبورتنج', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الحضرة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الأنفوشي', 'delivery_time' => '1-2 يوم'],
                ['name' => 'المنشية', 'delivery_time' => '1-2 يوم'],
                ['name' => 'أبو قير', 'delivery_time' => '1-3 أيام'],
                ['name' => 'السيوف', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الورديان', 'delivery_time' => '1-2 يوم'],
                ['name' => 'القباري', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الجميل', 'delivery_time' => '1-3 أيام'],
            ],
            'الدقهلية' => [
                ['name' => 'المنصورة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'ميت غمر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'السنبلاوين', 'delivery_time' => '1-3 أيام'],
                ['name' => 'دكرنس', 'delivery_time' => '1-3 أيام'],
                ['name' => 'بلقاس', 'delivery_time' => '1-3 أيام'],
                ['name' => 'نبروه', 'delivery_time' => '1-3 أيام'],
                ['name' => 'طلخا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'شربين', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الجمالية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'منية النصر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'بني عبيد', 'delivery_time' => '1-3 أيام'],
                ['name' => 'المنزلة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'تمي الأمديد', 'delivery_time' => '1-3 أيام'],
                ['name' => 'محلة دمنة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أجا', 'delivery_time' => '1-3 أيام'],
            ],
            'الشرقية' => [
                ['name' => 'الزقازيق', 'delivery_time' => '1-3 أيام'],
                ['name' => 'بلبيس', 'delivery_time' => '1-3 أيام'],
                ['name' => 'العاشر من رمضان', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبو كبير', 'delivery_time' => '1-3 أيام'],
                ['name' => 'منيا القمح', 'delivery_time' => '1-3 أيام'],
                ['name' => 'فاقوس', 'delivery_time' => '1-3 أيام'],
                ['name' => 'كفر صقر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبو حماد', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الإبراهيمية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'ههيا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'ديرب نجم', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أولاد صقر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الحسينية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'صان الحجر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'مشتول السوق', 'delivery_time' => '1-3 أيام'],
                ['name' => 'القنايات', 'delivery_time' => '1-3 أيام'],
            ],
            'البحيرة' => [
                ['name' => 'دمنهور', 'delivery_time' => '1-3 أيام'],
                ['name' => 'كفر الدوار', 'delivery_time' => '1-3 أيام'],
                ['name' => 'رشيد', 'delivery_time' => '1-3 أيام'],
                ['name' => 'إدكو', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبو المطامير', 'delivery_time' => '1-3 أيام'],
                ['name' => 'وادي النطرون', 'delivery_time' => '1-3 أيام'],
                ['name' => 'المحمودية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'إيتاي البارود', 'delivery_time' => '1-3 أيام'],
                ['name' => 'شبراخيت', 'delivery_time' => '1-3 أيام'],
                ['name' => 'كوم حمادة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'بدر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الدلنجات', 'delivery_time' => '1-3 أيام'],
                ['name' => 'النوبارية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'حوش عيسى', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبو حمص', 'delivery_time' => '1-3 أيام'],
            ],
            'الغربية' => [
                ['name' => 'طنطا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'المحلة الكبرى', 'delivery_time' => '1-3 أيام'],
                ['name' => 'كفر الزيات', 'delivery_time' => '1-3 أيام'],
                ['name' => 'بسيون', 'delivery_time' => '1-3 أيام'],
                ['name' => 'قطور', 'delivery_time' => '1-3 أيام'],
                ['name' => 'السنطة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'زفتى', 'delivery_time' => '1-3 أيام'],
                ['name' => 'سمنود', 'delivery_time' => '1-3 أيام'],
                ['name' => 'شرباص', 'delivery_time' => '1-3 أيام'],
            ],
            'المنوفية' => [
                ['name' => 'شبين الكوم', 'delivery_time' => '1-3 أيام'],
                ['name' => 'منوف', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أشمون', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الباجور', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الشهداء', 'delivery_time' => '1-3 أيام'],
                ['name' => 'تلا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'قويسنا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'بركة السبع', 'delivery_time' => '1-3 أيام'],
                ['name' => 'سرس الليان', 'delivery_time' => '1-3 أيام'],
                ['name' => 'ميت برة', 'delivery_time' => '1-3 أيام'],
            ],
            'القليوبية' => [
                ['name' => 'بنها', 'delivery_time' => '1-2 يوم'],
                ['name' => 'شبرا الخيمة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'قليوب', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الخانكة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'كفر شكر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'طوخ', 'delivery_time' => '1-3 أيام'],
                ['name' => 'القناطر الخيرية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'العبور', 'delivery_time' => '1-2 يوم'],
                ['name' => 'شبين القناطر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'كفر حمزة', 'delivery_time' => '1-3 أيام'],
            ],
            'الفيوم' => [
                ['name' => 'الفيوم', 'delivery_time' => '1-3 أيام'],
                ['name' => 'سنورس', 'delivery_time' => '1-3 أيام'],
                ['name' => 'طامية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'إطسا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبشواي', 'delivery_time' => '1-3 أيام'],
                ['name' => 'يوسف الصديق', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبوكساه', 'delivery_time' => '1-3 أيام'],
                ['name' => 'منشأة طامية', 'delivery_time' => '1-3 أيام'],
            ],
            'بني سويف' => [
                ['name' => 'بني سويف', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الواسطى', 'delivery_time' => '1-3 أيام'],
                ['name' => 'ناصر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أهناسيا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'ببا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الفشن', 'delivery_time' => '1-3 أيام'],
                ['name' => 'سمسطا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'مطر طارس', 'delivery_time' => '1-3 أيام'],
                ['name' => 'كوم أبو راضي', 'delivery_time' => '1-3 أيام'],
            ],
            'المنيا' => [
                ['name' => 'المنيا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'ملوي', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبو قرقاص', 'delivery_time' => '1-3 أيام'],
                ['name' => 'سمالوط', 'delivery_time' => '1-3 أيام'],
                ['name' => 'مطاي', 'delivery_time' => '1-3 أيام'],
                ['name' => 'مغاغة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'دير مواس', 'delivery_time' => '1-3 أيام'],
                ['name' => 'بني مزار', 'delivery_time' => '1-3 أيام'],
                ['name' => 'العدوة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'مبصر', 'delivery_time' => '1-3 أيام'],
            ],
            'أسيوط' => [
                ['name' => 'أسيوط', 'delivery_time' => '1-3 أيام'],
                ['name' => 'ديروط', 'delivery_time' => '1-3 أيام'],
                ['name' => 'منفلوط', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبنوب', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبو تيج', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الغنايم', 'delivery_time' => '1-3 أيام'],
                ['name' => 'ساحل سليم', 'delivery_time' => '1-3 أيام'],
                ['name' => 'صدفا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'البداري', 'delivery_time' => '1-3 أيام'],
                ['name' => 'القوصية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الفتح', 'delivery_time' => '1-3 أيام'],
            ],
            'سوهاج' => [
                ['name' => 'سوهاج', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أخميم', 'delivery_time' => '1-3 أيام'],
                ['name' => 'طهطا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'جرجا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'البلينا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'دار السلام', 'delivery_time' => '1-3 أيام'],
                ['name' => 'ساقلتة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'المراغة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'جهينة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'العسيرات', 'delivery_time' => '1-3 أيام'],
                ['name' => 'المنشأة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'طما', 'delivery_time' => '1-3 أيام'],
            ],
            'قنا' => [
                ['name' => 'قنا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'نجع حمادي', 'delivery_time' => '1-3 أيام'],
                ['name' => 'دشنا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'فرشوط', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبو تشت', 'delivery_time' => '1-3 أيام'],
                ['name' => 'قفط', 'delivery_time' => '1-3 أيام'],
                ['name' => 'نقادة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الوقف', 'delivery_time' => '1-3 أيام'],
                ['name' => 'قوص', 'delivery_time' => '1-3 أيام'],
                ['name' => 'شبين القبائل', 'delivery_time' => '1-3 أيام'],
            ],
            'الأقصر' => [
                ['name' => 'الأقصر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'البياضية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'القرنة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أرمنت', 'delivery_time' => '1-3 أيام'],
                ['name' => 'إسنا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الزينية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الطيبة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'كوم أمبو', 'delivery_time' => '1-3 أيام'],
                ['name' => 'المريس', 'delivery_time' => '1-3 أيام'],
            ],
            'أسوان' => [
                ['name' => 'أسوان', 'delivery_time' => '1-3 أيام'],
                ['name' => 'دراو', 'delivery_time' => '1-3 أيام'],
                ['name' => 'كوم أمبو', 'delivery_time' => '1-3 أيام'],
                ['name' => 'نصر النوبة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'إدفو', 'delivery_time' => '1-3 أيام'],
                ['name' => 'السباعية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبو سمبل', 'delivery_time' => '2-4 أيام'],
                ['name' => 'كلابشة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'البصيلية', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الرديسية', 'delivery_time' => '1-3 أيام'],
            ],
            'البحر الأحمر' => [
                ['name' => 'الغردقة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'مرسى علم', 'delivery_time' => '2-4 أيام'],
                ['name' => 'سفاجا', 'delivery_time' => '2-4 أيام'],
                ['name' => 'القصير', 'delivery_time' => '2-4 أيام'],
                ['name' => 'رأس غارب', 'delivery_time' => '2-4 أيام'],
                ['name' => 'الشلاتين', 'delivery_time' => '3-5 أيام'],
                ['name' => 'حلايب', 'delivery_time' => '3-5 أيام'],
                ['name' => 'مرسى علم القديمة', 'delivery_time' => '2-4 أيام'],
            ],
            'الوادي الجديد' => [
                ['name' => 'الخارجة', 'delivery_time' => '2-4 أيام'],
                ['name' => 'الداخلة', 'delivery_time' => '2-4 أيام'],
                ['name' => 'باريس', 'delivery_time' => '3-5 أيام'],
                ['name' => 'بلاط', 'delivery_time' => '3-5 أيام'],
                ['name' => 'الفرافرة', 'delivery_time' => '3-5 أيام'],
                ['name' => 'موط', 'delivery_time' => '2-4 أيام'],
            ],
            'مطروح' => [
                ['name' => 'مرسى مطروح', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الحمام', 'delivery_time' => '1-3 أيام'],
                ['name' => 'العلمين', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الضبعة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'سيوة', 'delivery_time' => '3-5 أيام'],
                ['name' => 'النجيلة', 'delivery_time' => '2-4 أيام'],
                ['name' => 'سيدي براني', 'delivery_time' => '3-5 أيام'],
                ['name' => 'السلوم', 'delivery_time' => '3-5 أيام'],
            ],
            'شمال سيناء' => [
                ['name' => 'العريش', 'delivery_time' => '2-4 أيام'],
                ['name' => 'بئر العبد', 'delivery_time' => '2-4 أيام'],
                ['name' => 'الشيخ زويد', 'delivery_time' => '2-4 أيام'],
                ['name' => 'رفح', 'delivery_time' => '2-4 أيام'],
                ['name' => 'نخل', 'delivery_time' => '3-5 أيام'],
                ['name' => 'الحسنة', 'delivery_time' => '3-5 أيام'],
            ],
            'جنوب سيناء' => [
                ['name' => 'شرم الشيخ', 'delivery_time' => '1-3 أيام'],
                ['name' => 'دهب', 'delivery_time' => '1-3 أيام'],
                ['name' => 'نويبع', 'delivery_time' => '1-3 أيام'],
                ['name' => 'طور سيناء', 'delivery_time' => '2-4 أيام'],
                ['name' => 'سانت كاترين', 'delivery_time' => '2-4 أيام'],
                ['name' => 'طابا', 'delivery_time' => '2-4 أيام'],
            ],
            'دمياط' => [
                ['name' => 'دمياط', 'delivery_time' => '1-3 أيام'],
                ['name' => 'رأس البر', 'delivery_time' => '1-3 أيام'],
                ['name' => 'فارسكور', 'delivery_time' => '1-3 أيام'],
                ['name' => 'كفر سعد', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الزرقا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'كفر البطيخ', 'delivery_time' => '1-3 أيام'],
                ['name' => 'عزبة البرج', 'delivery_time' => '1-3 أيام'],
            ],
            'بورسعيد' => [
                ['name' => 'بورسعيد', 'delivery_time' => '1-2 يوم'],
                ['name' => 'بورفؤاد', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الضواحي', 'delivery_time' => '1-2 يوم'],
                ['name' => 'جنوب بورسعيد', 'delivery_time' => '1-2 يوم'],
            ],
            'الإسماعيلية' => [
                ['name' => 'الإسماعيلية', 'delivery_time' => '1-2 يوم'],
                ['name' => 'فايد', 'delivery_time' => '1-3 أيام'],
                ['name' => 'التل الكبير', 'delivery_time' => '1-3 أيام'],
                ['name' => 'أبو صوير', 'delivery_time' => '1-3 أيام'],
                ['name' => 'القنطرة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'القنطرة غرب', 'delivery_time' => '1-3 أيام'],
                ['name' => 'نفيشة', 'delivery_time' => '1-3 أيام'],
                ['name' => 'وادي الملاك', 'delivery_time' => '1-3 أيام'],
            ],
            'السويس' => [
                ['name' => 'السويس', 'delivery_time' => '1-2 يوم'],
                ['name' => 'عتاقة', 'delivery_time' => '1-2 يوم'],
                ['name' => 'فيصل', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الأربعين', 'delivery_time' => '1-2 يوم'],
                ['name' => 'الجناين', 'delivery_time' => '1-3 أيام'],
                ['name' => 'بورتوفيق', 'delivery_time' => '1-2 يوم'],
            ],
            'كفر الشيخ' => [
                ['name' => 'كفر الشيخ', 'delivery_time' => '1-3 أيام'],
                ['name' => 'دسوق', 'delivery_time' => '1-3 أيام'],
                ['name' => 'بيلا', 'delivery_time' => '1-3 أيام'],
                ['name' => 'فوه', 'delivery_time' => '1-3 أيام'],
                ['name' => 'مطوبس', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الحامول', 'delivery_time' => '1-3 أيام'],
                ['name' => 'الرياض', 'delivery_time' => '1-3 أيام'],
                ['name' => 'سيدي سالم', 'delivery_time' => '1-3 أيام'],
                ['name' => 'قلين', 'delivery_time' => '1-3 أيام'],
                ['name' => 'بلطيم', 'delivery_time' => '1-3 أيام'],
                ['name' => 'مسير', 'delivery_time' => '1-3 أيام'],
            ],
            default => [],
        };

        foreach ($cities as $cityData) {
            City::create([
                'governorate_id' => $gov->id,
                'name' => $cityData['name'],
                'delivery_time' => $cityData['delivery_time'] ?? '1-3 أيام',
                'is_active' => true,
            ]);
        }
    }
}
